
export const storeProducts = [
  {
    id: 2,
    title: "Shea Butter",
    category: "BUTTERS",
    mini: 1000,
    regular: 2500,
    large: 4500,
    size:{ 
      mini: "(100g)",
      regular: "(250g)",
      large: "(500g)"
    },
    img: "img/shea_butter.jfif",
    description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
    contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    price: 12000,
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Avocado Butter",
    img: "img/avocado_butter.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    size: "mini.",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Mango Butter",
    img: "img/mango_butter.jfif",
    price: 12,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    size: "mini",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Cocoa Butter",
    img: "img/cocoa_butter.jfif",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    size: "mini",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Grapeseed Oil",
    img: "img/shea_butter.jfif",
    price: 12000,
    description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
    contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    size: "mini",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Olive Oil",
    img: "img/avocado_butter.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    size: "Mini.",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Carrot Oil",
    img: "img/mango_butter.jfif",
    price: 12,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    size: "Mini",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "Coconut Oil",
    img: "img/olive-oil.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    size: "Mini",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "Orange Oil (E)",
    img: "img/shea_butter.jfif",
    price: 12000,
    description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
    contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    size: "Mini",
    category: "ESSENTIAL OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "Lavender Oil (E)",
    img: "img/avocado_butter.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    size: "Mini",
    category: "ESSENTIAL OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 12,
    title: "Sandalwood Oil (E)",
    img: "img/mango_butter.jfif",
    price: 12,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    size: "Mini",
    category: "ESSENTIAL OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 13,
    title: "Rosehip Oil (E)",
    img: "img/olive-oil.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    size: "Mini",
    category: "ESSENTIAL OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
  id: 1,
  title: "Please Select a Product",
  img: "img/banner-image.png",
  price: 0,
  description: "",
  contains: "",
  usage: "",
  size: "",
  inCart: false,
  count: 0,
  total: 0
};

export const detailCat = {
  id: 14,
    title: "Premium Active Glow",
    img: "img/premium active glow set.jpg",
    price: 21000,
    description: "This collection is curated to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
};
export const collectionDetail = {
  id: 13,
  title: "Premium Active Glow",
    img: "img/premium active glow set.jpg",
    price: 21000,
    description: "This collection is curated to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  inCart: false,
  count: 0,
  total: 0
};

export const bestsellerProducts = [
  {
    id: 14,
    title: "Lightening Set",
    img: "img/lightening set.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 15,
    title: "Kids Care",
    img: "img/kids set.jpg",
    price: 12000,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 16,
    title: "Acne Set",
    img: "img/acne set.jpg",
    price: 14000,
    description: " This collection was put together to fight acne, improves discoloration on face and neck",
    contains: "One Detox face mask, One radiance face soap and One radiance face serum",
    usage: "Step 1: Mix half teaspoon of face mask with activator of choice. Apply generously on face and allow to dry but not crumbly, massage gently and then rinse off. Step 2: Massage soap as desired unto skin, then rinse off. Step 3: Apply face serum unto damp face and neck. BEST USED AT NIGHT!",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 17,
    title: "Basic Glow",
    img: "img/basic glow set.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  }
];
export const collections = [
  {
    id: 18,
    title: "Fresh Glow",
    img: "img/fresh glow set.jpg",
     price: 12000,
     description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
     contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 19,
    title: "Basic Glow",
    img: "img/basic glow set.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 20,
    title: "Kids Care",
    img: "img/kids set.jpg",
    price: 12000,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 21,
    title: "Lightening Set",
    img: "img/lightening set.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 22,
    title: "Acne Face Set",
    img: "img/acne set.jpg",
    price: 14000,
    description: " This collection was put together to fight acne, improves discoloration on face and neck",
    contains: "One Detox face mask, One radiance face soap and One radiance face serum",
    usage: "Step 1: Mix half teaspoon of face mask with activator of choice. Apply generously on face and allow to dry but not crumbly, massage gently and then rinse off. Step 2: Massage soap as desired unto skin, then rinse off. Step 3: Apply face serum unto damp face and neck. BEST USED AT NIGHT!",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 23,
    title: "Active Glow",
    img: "img/active glow set.jpg",
    price: 12000,
    description: "This collection is designed for face and body lightening, it helps with hyperpigmentation and evens out skin tone",
    contains: "One turmeric soap, One light radiance lotion and One radiance face milk",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 24,
    title: "Repair Set",
    img: "img/anti aging set.jpg",
    price: 11000,
    description: "This collection was carefully put together with products made to repair damaged skin, smoothen wrinkled skin and delay the signs of aging ",
    contains: "One estelle black soap, One body souffle and One radiant face milk",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply body lotion on damp skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    inCart: false,
    count: 0,
    total: 0
  }
  ];

export const butters = [
  {
    id: 18,
    title: "Shea Butter",
    img: "img/shea_butter.jfif",
    price: 12000,
    description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
    contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 19,
    title: "Avocado Butter",
    img: "img/avocado_butter.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 20,
    title: "Mango Butter",
    img: "img/mango_butter.jfif",
    price: 12,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 21,
    title: "Cocoa Butter",
    img: "img/cocoa_butter.jfif",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  }
];

export const butterDetail = {
    id: 19,
      title: "Cocoa Butter",
      img: "img/cocoa_butter.jfif",
      price: 210,
      description: "Avo avo my friend.",
      contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
      usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
      life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
      category: "BUTTERS",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  };


export const oils = [
  {
    id: 22,
    title: "Grapeseed Oil",
    img: "img/shea_butter.jfif",
    price: 12000,
    description: "Specially curated to gently brighten face and body, soften the skin and improve skin radiance",
    contains: "One estelle black soap, One radiance lotion(melanin/caramel) and One radiance face milk",
    usage: "Step 1: Apply soap unto skin for 5minutes, then rinse off. Step 2: Apply face milk on face and neck.  Step 3: Apply lotion on body.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 23,
    title: "Olive Oil",
    img: "img/avocado_butter.jpg",
    price: 5000,
    description: "Specially curated to brighten dull skin by exfoliating the skin, keeping it moisturized and help to fade stretch marks",
    contains: "One shea glow polish and One shea glow oil",
    usage: "Step 1: Massage desired quantity of shea glow polish unto skin for 5minutes, then rinse off. Step 2: Apply shea glow oil on damp skin, immediately after exfoliating.  CAUTION:DO NOT Apply on your face if you have breakouts.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 24,
    title: "Carrot Oil",
    img: "img/mango_butter.jfif",
    price: 12,
    description: "Carefully put together to ensure that your children's skin is properly cleansed, moisturized and protected. this combination improves skin conditions such as dry skin and eczema",
    contains: "One noono kids soap, One kooko body butter and One chiis body oil",
    usage: "Step 1: Apply soap unto skin, then rinse off. Step 2: Apply body butter on damp skin.  Step 3: Apply body oil on hair and skin.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  },
  {
    id: 25,
    title: "Coconut Oil",
    img: "img/olive-oil.jpg",
    price: 24000,
    description: "This collection is specifically created to clarify and unify your complexion, lighten the skin visibly up to two shades. Enjoy even toned skin with a flawless finish.",
    contains: "One soap, One lotion and One face milk. each set comes with a free shea glow polish",
    usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face milk unto face and neck.  Step 3: Apply body lotion on damp skin. EXFOLIATE WITH SHEA GLOW POLISH AT LEAST TWICE A WEEK.",
    life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
    category: "CARRIER OIL",
    inCart: false,
    mini: 1000,
    regular: 2500,
    large: 4500,
    count: 0,
    total: 0
  }
];

export const oilDetail = {
  id: 23,
  title: "Olive Oil",
  img: "img/olive-oil.jpg",
  price: 210,
  description: "Avo avo my friend.",
  contains: "One turmeric soap, One shea glow polish, One light radiance lotion and One radiance face serum",
  usage: "Step 1: Massage desired quantity of body polish unto skin, leave for 5 minutes and then rinse off. Step 3: Apply soap unto skin before bath, then rinse off. Step 4: Apply face serum unto face and neck.  Step 3: Apply body lotion on damp skin.",
  life: "Keep out of reach of children. Discontinue if skin irritation occurs. Do not use on open or split skin. For external use only.",
  category: "CARRIER OIL",
  inCart: false,
  mini: 1000,
  regular: 2500,
  large: 4500,
  count: 0,
  total: 0
};

export const lookup = {
  "Abuja": 1000,
  "Lagos": 1500,
  "Ibadan": 2000,
  "Portharcourt": 1500,
  "Benin": 1500,
  "Owerri": 2000,
  "Asaba": 2000,
  "Minna": 1500,
  "Jos": 2000,
  "Kaduna": 1500,
  "Aba":2000,
  "Uyo":2000,
  "Onitsha":2000,
  "Markudi":2000,
  "Calabar":2000,
  "Ikot":2000,
  "Warri":2000,
  "Enugu":2000,
  "Auchi":1500,
  "Akure":2000,
  "Kano":2000,
  "Mararaba":1500,
  "adamawa": 2500
}